name: Publish Docker Images
on:
  push:
    branches:
      - master
    tags:
      - "v*"
permissions:
  packages: write
concurrency:
  group: dockerpub-${{ format('{0}-{1}', github.ref_name || github.run_number, github.job) }}
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout App Release Tag
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

          token: ${{ secrets.REPO_TOKEN }}
      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./.github/actions/build-image
        id: build-image
        with:
          target: release
          token: ${{ secrets.REPO_TOKEN }}
      - name: Upload frontend build artifacts to release if a tag is pushed
        if: startsWith(github.ref, 'refs/tags')
        run: |
          gh release upload ${{ github.ref_name }} \
            ${{ steps.build-image.outputs.frontend_bundle }}
