on:
  push:
    branches:
      - master
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-24.04
    steps:
      - shell: bash
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >> "$GITHUB_ENV"
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.REPO_TOKEN }}
      - name: Update appVersion in helm chart
        if: ${{ steps.release.outputs.release_created }}
        run: |
          sed -i "s|appVersion: .*|appVersion: ${{ steps.release.outputs.version }}|" helm/Chart.yaml
          git config --global user.name "Brian Adams"
          git config --global user.email "adamsb@msu.edu"
          git add helm/Chart.yaml
          git commit -m "fix(helm): Update to appVersion ${{ steps.release.outputs.version }}"
          git push
